# Only depend on RIOT internal modules here
ifneq (,$(filter gui,$(USEMODULE)))
  USEPKG += lvgl
  USEMODULE += xtimer
  USEMODULE += event
  USEMODULE += lvgl_core
  USEMODULE += lvgl_objx
  USEMODULE += lvgl_misc
  USEMODULE += lvgl_themes
  USEMODULE += lvgl_draw
  USEMODULE += lvgl_font
  USEMODULE += lvgl_hal
  USEMODULE += core_thread_flags
endif

ifneq (,$(filter controller,$(USEMODULE)))
  FEATURES_REQUIRED += periph_wdt
endif

ifneq (,$(filter hal,$(USEMODULE)))
  USEMODULE += ili9341
  USEMODULE += cst816s
  USEMODULE += hal_input
  FEATURES_REQUIRED += periph_adc
  FEATURES_REQUIRED += periph_gpio
endif

ifneq (,$(filter util,$(USEMODULE)))
  USEMODULE += core_thread_flags
endif

ifneq (,$(filter widget,$(USEMODULE)))
endif

ifneq (,$(filter fsman,$(USEMODULE)))
  USEMODULE += vfs
  USEPKG += littlefs
endif

ifneq (,$(filter bleman,$(USEMODULE)))
  USEPKG += nimble
  USEMODULE += nimble_tinycrypt
  USEMODULE += nimble_host_store_ram
  USEMODULE += nimble_host
  USEMODULE += nimble_controller
  USEMODULE += nimble_svc_gap
  USEMODULE += nimble_svc_gatt
  USEMODULE += bluetil_ad

  USEMODULE += core_thread_flags
  USEMODULE += luid
  USEMODULE += fmt
  USEMODULE += event_timeout
endif
