# Base application makefile

RIOTBASE ?= $(PINETIMEBASE)/RIOT

WIDGETDIR ?= $(PINETIMEBASE)/widgets
PINEMODULEDIR ?= $(PINETIMEBASE)/modules

# Ensures the Makefile.dep is used in the dependency resolution
#
EXTERNAL_MODULE_DIRS += $(PINEMODULEDIR)
# Early include
include $(PINEMODULEDIR)/Makefile.include

include $(WIDGETDIR)/Makefile.include

include $(RIOTBASE)/Makefile.include
