# Base application makefile

RIOTBASE ?= $(PINETIMEBASE)/RIOT

WIDGETDIR ?= $(PINETIMEBASE)/widgets

include $(PINETIMEBASE)/modules/Makefile.include

include $(WIDGETDIR)/Makefile.include

include $(RIOTBASE)/Makefile.include
