USEPKG += lvgl
USEMODULE += xtimer
USEMODULE += event

USEMODULE += lvgl_core
USEMODULE += lvgl_objx
USEMODULE += lvgl_misc
USEMODULE += lvgl_themes
USEMODULE += lvgl_draw
USEMODULE += lvgl_font
USEMODULE += lvgl_hal

# screens
USEMODULE += screen_time
USEMODULE += screen_menu
